* TODO Finish website
  * Immediate Goals
    ** increase spacing slightly between three "menu" bars and the "Close menu" text
    ** put "topics" next to the three bars for team names
    ** try to co-opt someone per article to read it from an outside group, to prevent groupthink
    ** add style guide for references, in-line lists, using e.g. <h3> tags (###) for section titles, where to put captions, etc.
    ** collect footnote-clicking statistics ;)
    ** twitter button should go to twitter page
    ** article should be shareable via twitter
    ** Make sure to uncomment Stanford's name after club app goes through (2 places)
    ** sort team names in pop-out menu
    ** include link to science dictionary at bottom of the pop-out menu and
    ** move facebook like and twitter buttons to the post itself, and make them point to each specific article instead of to the webpage as a whole
    ** set up google analytics
  * Large Goals
    ** set up a SQL server using sqlalchemy to store the articles
      *** Create database
      *** various things become more manageable once this is done:
        **** actually sort posts
        **** actually track pageviews
        **** pagination.
        **** Make sure to switch to first 5 most popular posts and first 10 most recent posts
    ** make a page to look at a specific author's articles, with optional bio at top
      *** hook up author links
    ** don't let website fail on startup if there's a bad post file
  * Strech Goals
    ** Wikipedia style pop-up links for desktop version
    ** make it so that an author can actually have a different headshot for each post they make
    ** and actually have a different nickname for each post
    ** and make it so that declaring authorship is actually optional. I don't want to do it via a "faux" author which matches the team name, because then the author page would for that faux author would be very confusing. maybe make it via a "faux" author called "Team Name (anonymous)"
    ** ?Login system? + comments
    ** Post list page
    ** Science dictionary
      *** pop-up definitions inline
    ** Search box
  * URL Scheme:
    http://thedishonscience.com/topics/$topic_name
    http://thedishonscience.com/posts/$post_name
    http://thedishonscience.com/author/$author_name

